### ISSUE TITLE
Using the fittest agent

### ISSUE THREAD

**Issue by rohithsaro** [shepai/Biped#1]
How can you save and use the weights of the fittest agent so that the robot can 'walk ' with those weights on command ?

**Comment by shepai** [comment]
The genotype that encodes the weights and biases is saved in a numpy object. You can use:

`np.save(genotype,"path/to/file")`
Where genotype is the genotype with the best fitness.

Then you can open the file up again as a numpy object and use the 
`agent.set_genes(opened_numpy)`
